### ISSUE TITLE
Missing required parameter $code

### ISSUE THREAD

**Issue by ansidev** [andela-iadeniyi/laravel-accountkit#3]
Please view this link:
https://github.com/andela-iadeniyi/laravel-accountkit/blob/master/src/FacebookAccountKit.php#L67

You declare function getAccessToken($code) at
https://github.com/andela-iadeniyi/laravel-accountkit/blob/master/src/FacebookAccountKit.php#L55
but you called it without any parameter.

**Comment by andela-iadeniyi** [comment]
Thanks for pointing that out, I haven't work on it for a while now.
