### ISSUE TITLE
This authorization code has been used

### ISSUE THREAD

**Issue by paulprok** [andela-iadeniyi/laravel-accountkit#8]
That message I get in 99%.
So, in method _accountKitData_ we request graph twice:
```
$data = $this->data($code);
$token = $this->getAppToken($code);
```
So in second request we get from graph 
> This authorization code has been used

**Comment by andela-iadeniyi** [comment]
Issue resolved, please update your package to version `1.2` which come with the fix.

**Comment by paulprok** [comment]
thanx, got it
